matrix:
  include:
    - language: ruby
      rvm:
        - 2.4.4
        - 2.5
        - 2.6
      script:
        - bundle exec rubocop
        - bundle exec rspec

    - language: node_js
      node_js:
        - node
      script:
        - yarn run eslint
      cache:
        yarn: true
        directories:
          - node_modules
